site:
  title: Kubewarden
  start_page: 1.27@kubewarden:en:introduction.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_paths: [shared, docs/version-1.26, docs/version-1.25]
      #start_paths: [shared, docs/version-*]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./kw-community-docs-supp-files

asciidoc:
  attributes:
    page-draft-preview-only: 'You can have anything here, just not empty - so this is true, if empty string, or absent, then - false'
    kw-build-type: 'community' # 'community' or 'product'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>


output:
  dir: build-local-community/site
