site:
  title: SUSE Security Admission Controller
  start_page: 1.29@admission-controller:en:introduction.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_paths: [shared, docs/version-*]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    kw-build-type: 'product' # 'community' or 'product'
    kw-rancher-product-name: 'SUSE Security Admission Controller'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true

output:
  dir: build/site
