site:
  title: Kubewarden
  start_page: 1.23@kubewarden:en:introduction.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_paths: [shared, docs/version-*]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./kw-community-docs-supp-files

asciidoc:
  attributes:
    kw-build-type: 'community' # 'community' or 'product'
    kw-rancher-product-name: 'SUSE® Rancher Prime Policy Manager'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>


output:
  dir: build-community/site
