site:
  title: SUSE® Rancher Prime Policy Manager
  start_page: 1.20@policy-manager:en:introduction.adoc

content:
  sources:
    - url: https://github.com/rancher/kubewarden-product-docs.git
      branches: [main]
      start_paths: [shared, docs/next, docs/version-*]

ui:
  bundle:
    url: tmp/sp
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    kw-build-type: 'product' # 'community' or 'product'
    kw-rancher-product-name: 'SUSE® Rancher Prime Policy Manager'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
