site:
  title: SUSE® Rancher Prime Policy Manager
  start_page: 1.29@policy-manager:en:introduction.adoc

content:
  sources:
    - url: https://github.com/rancher/kubewarden-product-docs.git
      branches: [main]
      start_paths: [shared, docs/version-*]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-draft-preview-only: 'true'
    kw-build-type: 'product' # 'community' or 'product'
    kw-rancher-product-name: 'SUSE® Rancher Prime: Admission Policy Manager (Kubewarden)'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [en] # ko not supported by extension
      index_latest_only: true
    - require: '@sntke/antora-mermaid-extension' # <1>
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>
    - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
      attributefile: ./product-docs-common/global-attributes.yml
      enabled: true

output:
  dir: build/site
