site:
  title: Kubewarden
  start_page: 1.25@kubewarden:en:introduction.adoc

content:
  sources:
    #- url: https://github.com/rancher/kubewarden-product-docs.git
    - url: ./
      branches: HEAD
      # Branches need to be HEAD, not [main]. For remote community build to
      # work. To do with the switching of antora.yml files between product and
      # community. Not exactly clear why this is necessary though.
      start_paths: [shared, docs/version-*]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./kw-community-docs-supp-files

asciidoc:
  attributes:
    page-draft-preview-only: 'true'
    kw-build-type: 'community' # 'community' or 'product'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>


output:
  dir: build-remote-community/site
