include::partial$variables.adoc[]
= Was ist {project-name}?
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: Introducing {project-name}, a SUSE® Rancher Prime product.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["introduction"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"]
:sidebar_label: Introduction
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} ist eine Kubernetes Policy Engine. Ihr Ziel ist es, die universelle Policy Engine für Kubernetes zu sein.

{intro-paragraph}

Hier ist ein Link zur Übersicht der Rancher-Produktdokumentation:

* xref:rancher-manager:de:/about-rancher/overview.adoc[Übersicht]

== Wie hilft {project-name}?

{short-project-name} bietet Flexibilität bei der Zulassung und Durchsetzung von Richtlinien in einer Kubernetes-Umgebung.

=== Vorteile und Wert

- Verwenden Sie eine beliebige Programmiersprache, die https://webassembly.org[WebAssembly]-Binärdateien erzeugt, um Ihre Richtlinien zu schreiben.
- WebAssembly ermöglicht die Kompatibilität von Richtlinien über Prozessoren und Betriebssysteme hinweg.
- Wiederverwendung von Richtlinien aus anderen Policy-Engines, ohne dass sie neu geschrieben werden müssen.
- Verteilen Sie Richtlinien über standardmäßige und sichere Mechanismen wie https://opencontainers.org[OCI]-konforme Registries.
- Die Durchsetzung von Richtlinien bei der Zulassung stellt sicher, dass nur konforme Workloads ausgeführt werden.
- Der {short-project-name}-Audit-Scanner überprüft aktiv und kontinuierlich die Einhaltung der Richtlinien im Laufe der Zeit.
- Überprüfen Sie Richtlinien mit https://slsa.dev[SLSA] (Supply Chain Levels for Software Artifacts) Tools und Praktiken.
- {project-name} bietet einen umfassenden Ansatz für das Management von Zulassungsrichtlinien.
- Die CNCF-Mitgliedschaft und eine wachsende Open-Source-Community und ein wachsendes Ökosystem helfen {short-project-name} bei Transparenz, Zusammenarbeit und Verbesserung.

=== Anwendungsfälle

- Sicherheitshärtung. Erzwingen Sie beispielsweise Richtlinien, die Container-Privilegien einschränken, Netzwerkrichtlinien durchsetzen oder unsichere Image-Registries blockieren.
- Compliance-Auditing. Stellen Sie sicher, dass Workloads den organisatorischen oder regulatorischen Standards und Best Practices entsprechen.
- Ressourcenoptimierung. Erzwingen Sie Ressourcenlimits und -quoten.

Weitere Dokumentationen zu Anwendungsfällen finden Sie auf der Seite xref:use-cases.adoc[Anwendungsfälle].

== Neu bei {short-project-name}?

Wenn Sie neu im {short-project-name}-Projekt sind, beginnen Sie mit der xref:quick-start.adoc[Schnellstartanleitung] und der Seite xref:explanations/architecture.adoc[Architektur]. Dann hängt es davon ab, wohin Ihre Interessen Sie führen. Für Richtlinienentwickler gibt es sprachspezifische Abschnitte in den Tutorials. Für Integratoren und Administratoren gibt es einen 'How-tos'-Abschnitt. Der Erklärungsabschnitt enthält nützliches Hintergrundmaterial. Es gibt auch ein xref:glossary.adoc[Glossar].

== Was ist WebAssembly?

Wie auf der https://webassembly.org/[offiziellen Website von WebAssembly] angegeben:

____
WebAssembly (abgekürzt Wasm) ist ein binäres Befehlsformat für eine stackbasierte virtuelle Maschine. Wasm ist als portables Kompilierungsziel für Programmiersprachen konzipiert und ermöglicht den Einsatz im Web für Client- und Serveranwendungen.
____

Wasm wurde ursprünglich als Browser-"Erweiterung" konzipiert. Die WebAssembly-Community bemüht sich jedoch, die Ausführung von Wasm-Code außerhalb von Browsern zu ermöglichen.

== Warum WebAssembly verwenden?

Benutzer können Kubernetes-Richtlinien in ihrer bevorzugten Programmiersprache schreiben, sofern deren Toolchain Wasm-Binärdateien generieren kann.

Wasm-Module sind portabel, einmal erstellt können sie auf jeder Art von Prozessorarchitektur und Betriebssystem ausgeführt werden. Zum Beispiel kann eine auf Apple Silicon entwickelte und erstellte Richtlinie ohne Konvertierung auf AMD64/Intel64 Linux ausgeführt werden.

Richtlinienautoren können ihre Fähigkeiten, Werkzeuge und Best Practices wiederverwenden. Richtlinien sind "traditionelle" Programme, die wiederverwendbare Blöcke (reguläre Bibliotheken) haben können. Sie können sie linten und testen und sie in aktuelle CI- und CD-Workflows einbinden.

== Richtlinienverteilung

Sie können {short-project-name}-Richtlinien über einen Standard-Webserver bereitstellen oder, noch besser, sie in einer OCI-konformen Registry als https://github.com/opencontainers/artifacts[OCI-Artefakte] veröffentlichen.

ifeval::["{build-type}" == "community"]

== Herstellerneutralität

{short-project-name} ist ein link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/[herstellerneutrales] Projekt, wie von der CNCF definiert.

endif::[]
