include::partial$variables.adoc[]
= Organización de la documentación
:revdate: 2025-11-10
:page-revdate: {revdate}
:sidebar_label: Organization
:sidebar_position: 75
:description: How is the {project-name} documentation organized?
:keywords: ["admission policy manager", "{project-name}", documentation, organization]
:doc-persona: [kubewarden-all]
:doc-type: [explanation]
:doc-topic: [explanation]

{project-name} organiza la documentación del proyecto de la siguiente manera:

* xref:/introduction.adoc[Introducción]
* xref:/quick-start.adoc[Inicio rápido]
* _Tutoriales_—aprendizaje a través de ejemplos.
* _Explicaciones_—conceptos subyacentes.
* _Guías prácticas_—realización de tareas de {short-project-name}.
* _Referencia_
* Organización—esta página
* xref:/personas.adoc[Personas]—¿para quién es {short-project-name}?
* xref:/disclosure.adoc[Seguridad]
* xref:/glossary.adoc[Glosario]

La mayor parte del material se encuentra en las cuatro secciones, _Tutoriales_, _Explicaciones_, _Guías prácticas_ y _Referencia_. Puede haber superposición, ya que las secciones no son mutuamente excluyentes. El proyecto {short-project-name} intenta seguir el marco de documentación link:https://diataxis.fr/[Diátaxis].

== Navegación

El menú de contenidos de la izquierda siempre indica la ubicación actual de su documento. El menú de secciones de la derecha muestra las secciones de la página actual. También hay una función de 'migas de pan' en la parte superior del panel de contenido principal de cada página.

== Búsqueda

En el panel de cabecera de cada página hay un cuadro de búsqueda.

== Edición

En la parte inferior de cada página hay un enlace al código fuente de la página en GitHub.

== Otros recursos

También se mantienen:

* link:https://github.com/kubewarden/rfc[RFCs] para el proyecto.
* Una serie de link:https://www.kubewarden.io/blog/[entradas de blog] relacionadas con los lanzamientos de {community-name}.
* Elementos relacionados con la link:https://github.com/kubewarden/community[gestión de la comunidad] de {community-name}.
