include::partial$variables.adoc[]
= Inicio rápido
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: Getting started with {project-name}, installing the {project-name} stack and taking care of prerequisites and authentication
:doc-persona: ["kubewarden-all"]
:doc-topic: ["quick-start"]
:doc-type: ["tutorial"]
:keywords: ["{project-name}", "installation", "quick start", "policyserver", "clusteradmissionpolicy", "admissionpolicy"]
:sidebar_label: Quick start
:sidebar_position: 20
:current-version: {page-origin-branch}

++++
<head>
<script async src="https://artifacthub.io/artifacthub-widget.js"></script>
</head>
++++

La pila de {project-name} se compone de:

* Uno o más recursos {cluster-admission-policy}: esto define las políticas para los clústeres de Kubernetes.
* Uno o más recursos {policy-server}: que representan un despliegue de un `PolicyServer` de {short-project-name}. El `PolicyServer` de {short-project-name} carga y evalúa las políticas de su administrador.
* Uno o más recursos {admission-policy}: políticas para un espacio de nombres definido.
* Un despliegue de un `kubewarden-controller`: este controlador supervisa los recursos {cluster-admission-policy} e interactúa con los componentes {policy-server} de {short-project-name}.

[TIP]
====

{short-project-name} describe sus Definiciones de Recursos Personalizados (CRD) de Kubernetes xref:reference/CRDs.adoc[aquí].

Las CRD de {short-project-name} mencionadas en este tutorial y en el resto de la documentación tienen nombres cortos, que son más fáciles de usar. Estos son los nombres cortos de las CRD:

[cols="1,1"]
|===
| Recurso | nombreCorto

| AdmissionPolicies
| *ap*

| ClusterAdmissionPolicies
| *cap*

| AdmissionPolicyGroups
| *apg*

| ClusterAdmissionPolicyGroups
| *capg*

| PolicyServers
| *ps*

|===

====


== Instalación

[IMPORTANT]
.Autenticación
====

:gh-pat-url: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

Puede recuperar las políticas de {short-project-name} del registro de contenedores de GitHub en https://ghcr.io. Necesita autenticación para usar el repositorio con la CLI de {short-project-name}, un {gh-pat-url}[token de acceso personal de GitHub] (PAT). Su documentación le guía a través de la creación de uno si aún no lo ha hecho. A continuación, se autentica con un comando como:

[subs="+attributes", console]
----
echo $PAT | docker login ghcr.io --username <mi-usuario-gh> --password-stdin
----

====


Despliegue la pila de {short-project-name} usando los charts de `helm` de la siguiente manera:

[subs="+attributes", console]
----
helm repo add kubewarden https://charts.kubewarden.io
----

[subs="+attributes", console]
----
helm repo update kubewarden
----

Instale los siguientes charts de Helm en el espacio de nombres `kubewarden` de su clúster de Kubernetes:

* `kubewarden-crds`, que registra las Definiciones de Recursos Personalizados {cluster-admission-policy}, {admission-policy} y {policy-server}. También, las Definiciones de Recursos Personalizados {report} utilizadas por el escáner de auditoría.
* `kubewarden-controller`, que instala el controlador de {short-project-name} y el escáner de auditoría
+
[NOTE]
====

Si necesita deshabilitar el componente del escáner de auditoría, consulte la xref:howtos/audit-scanner.adoc[página de documentación] de instalación del escáner de auditoría.

====
+
* `kubewarden-defaults`, que crea un recurso `PolicyServer` llamado `default`. También puede instalar un conjunto de políticas recomendadas para proteger su clúster mediante la aplicación de buenas prácticas conocidas.

[subs="+attributes", console]
----
helm install --wait -n kubewarden --create-namespace kubewarden-crds kubewarden/kubewarden-crds
----

[subs="+attributes", console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller
----

[subs="+attributes", console]
----
helm install --wait -n kubewarden kubewarden-defaults kubewarden/kubewarden-defaults
----

[CAUTION]
====

Desde https://github.com/kubewarden/kubewarden-controller/releases/tag/v0.4.0[`v0.4.0`], no se crea un recurso `PolicyServer` llamado `default` usando el chart `kubewarden-controller`. Ahora un chart de Helm llamado `kubewarden-defaults`, instala el servidor de políticas predeterminado.

Esto significa que si no se utiliza la última versión del `kubewarden-controller` al actualizar o eliminar, su servidor de políticas predeterminado no se actualiza ni se elimina. Por lo tanto, podría tener problemas si intenta instalar `kubewarden-defaults` con información contradictoria, por ejemplo, el mismo nombre de servidor de políticas. Para instalar futuras actualizaciones del chart de Helm `kubewarden-defaults`, elimine el recurso `PolicyServer` existente creado por el `kubewarden-controller` antes de instalar el nuevo chart. Ahora puede actualizar su servidor de políticas utilizando las actualizaciones de Helm sin conflictos de recursos. Cuando elimina el `PolicyServer`, también elimina todas las políticas vinculadas a él.

====


Los valores de configuración predeterminados son suficientes para la mayoría de los despliegues. La https://charts.kubewarden.io/#configuration[documentación] describe todas las opciones.

== Componentes principales

{short-project-name} tiene tres componentes principales con los que interactúa:

* El {policy-server}
* El {cluster-admission-policy}
* El {admission-policy}

=== `PolicyServer`

El `kubewarden-controller` gestiona un `PolicyServer` de {short-project-name}. Puede desplegar múltiples {policy-server}s en el mismo clúster de Kubernetes.

Un `PolicyServer` valida las solicitudes entrantes ejecutando políticas de {short-project-name} contra ellas.

Esta es la configuración predeterminada de `PolicyServer`:

[subs="+attributes", yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: ghcr.io/kubewarden/policy-server:v1.3.0
  replicas: 2
  serviceAccountName: ~
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: debug
----

[NOTE]
====

Compruebe la https://github.com/kubewarden/policy-server/pkgs/container/policy-server[última versión publicada de `PolicyServer`] y cambie la etiqueta para que coincida.

====

Resumen de los atributos del recurso `PolicyServer`:

[cols="^,,"]
|===
| Requerido | Marcador de posición | Descripción

| Y
| `image`
| El nombre de la imagen del contenedor

| Y
| `replicas`
| El número de instancias deseadas

| N
| `serviceAccountName`
| El nombre de la `ServiceAccount` a utilizar para el despliegue del `PolicyServer`. Si
  no se proporciona ningún valor, se utiliza la `ServiceAccount` predeterminada del espacio de nombres de instalación de `kubewarden-controller`.

| N
| `env`
| La lista de variables de entorno

| N
| `annotations`
| La lista de anotaciones

|===

Cambiar cualquiera de estos atributos provoca un despliegue de `PolicyServer` con la nueva configuración.

=== ClusterAdmissionPolicy

El recurso {cluster-admission-policy} es el núcleo de la pila de {short-project-name}. Define cómo las políticas evalúan las solicitudes.

La aplicación de políticas es la operación más común que realiza un administrador de Kubernetes. Puede declarar tantas políticas como desee, cada una dirigida a uno o más recursos de Kubernetes (es decir, `pods`, `Recursos Personalizados` y otros). También especifica el tipo de operaciones aplicadas a los recursos de destino. Las operaciones disponibles son `CREATE`, `UPDATE`, `DELETE` y `CONNECT`.

Configuración predeterminada de {cluster-admission-policy}:

[subs="+attributes", yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psp-capabilities
spec:
  policyServer: reserved-instance-for-tenant-a
  module: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.9
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  settings:
    allowed_capabilities:
      - CHOWN
    required_drop_capabilities:
      - NET_ADMIN
----

Resumen de los atributos del recurso {cluster-admission-policy}:

[cols="^,,"]
|===
| Requerido | Marcador de posición | Descripción

| N
| `policy-server`
| Identifica un objeto `PolicyServer` existente. Solo
  esta instancia de `PolicyServer` sirve la política. El servidor de políticas llamado `default` sirve un {cluster-admission-policy} sin un `PolicyServer` explícito.

| Y
| `module`
| La ubicación de la política de {short-project-name}. Se permiten los siguientes esquemas:

| N
|
| - `registry`: Descarga de políticas desde un
    registro de contenedores compatible con https://github.com/opencontainers/artifacts[artefactos OCI].
    Ejemplo: `registry://<URL del registro/política OCI>`

| N
|
| - `http`, `https`: Descarga de políticas desde un servidor HTTP(s) regular.
    Ejemplo: `\https://<URL del sitio web/política>`

| N
|
| - `file`: Carga la política desde un archivo en el sistema de archivos del ordenador.
    Ejemplo: `\file:///<ruta completa del binario WASM de la política>`

| Y
| `resources`
| Los recursos de Kubernetes evaluados por la política

| Y
| `operations`
| Qué operaciones para los tipos dados anteriormente deben ser reenviadas a esta
  política de admisión por el servidor de la API para su evaluación.

| Y
| `mutating`
| Establezca este valor booleano en `true` para las políticas que pueden mutar
  las solicitudes entrantes

| N
| `settings`
| Un objeto de formato libre que contiene los valores de configuración de la política

| N
| `failurePolicy`
| La acción a tomar si la solicitud evaluada por una política resulta en un error.
  Se permiten las siguientes opciones:

| N
|
| - `Ignore`: ignora un error al llamar al webhook y la solicitud de la API
    continúa.

| N
|
| - `Fail`: un error al llamar al webhook hace que la admisión falle
    y se rechace la solicitud de la API.
|===

[NOTE]
====

El controlador registra el `scope` del webhook `*` de los recursos {cluster-admission-policy}. Esto significa que los webhooks registrados reenvían todas las solicitudes que coinciden con los `resources` y `operations` dados, ya sean recursos con espacio de nombres o de todo el clúster.

====


=== AdmissionPolicy

{admission-policy} es un recurso de todo el espacio de nombres. La política procesa solo las solicitudes que se dirigen al espacio de nombres con el {admission-policy} definido. Aparte de eso, no hay diferencias funcionales entre los recursos {admission-policy} y {cluster-admission-policy}.

[IMPORTANT]
====

{admission-policy} requiere Kubernetes 1.21.0 o superior. Esto se debe a que {short-project-name} utiliza la etiqueta `kubernetes.io/metadata.name`, introducida en Kubernetes 1.21.0

====

La documentación completa de estos Recursos Personalizados está https://github.com/kubewarden/kubewarden-controller/blob/main/docs/crds/README.asciidoc[aquí] o en https://doc.crds.dev/github.com/kubewarden/kubewarden-controller[docs.crds.dev].

== Ejemplo: Aplicar su primera política

Usaremos la política https://github.com/kubewarden/pod-privileged-policy[`pod-privileged`]. Queremos evitar la creación de contenedores privilegiados dentro de nuestro clúster de Kubernetes aplicando esta política.

Definamos un {cluster-admission-policy} para hacer eso:

[subs="+attributes", console]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
EOF
----

Esto produce la siguiente salida:

[subs="+attributes", console]
----
clusteradmissionpolicy.policies.kubewarden.io/privileged-pods created
----

Después de instanciar un {cluster-admission-policy}, el estado se vuelve `pending`, y fuerza un despliegue del `PolicyServer` de destino. En el ejemplo, es el `PolicyServer` llamado `default`. Puede supervisar el despliegue ejecutando el siguiente comando:

[subs="+attributes", console]
----
kubectl get clusteradmissionpolicy.policies.kubewarden.io/privileged-pods
----

Debería ver la siguiente salida:

[subs="+attributes", console]
----
NAME              POLICY SERVER   MUTATING   STATUS
privileged-pods   default         false      pending
----

Una vez que la nueva política está lista, el `kubewarden-controller` registra un objeto https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io[ValidatingWebhookConfiguration] para servirla.

El estado de {cluster-admission-policy} se vuelve `active` una vez que el Despliegue se completa para cada instancia de `PolicyServer`. Muestre los {validating-webhook-configuration}s con el siguiente comando:

[subs="+attributes", console]
----
kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -l kubewarden
----

Debería ver la siguiente salida:

[subs="+attributes", console]
----
NAME                          WEBHOOKS   AGE
clusterwide-privileged-pods   1          9s
----

Una vez que el {cluster-admission-policy} está activo y el {validating-webhook-configuration} se registra, puede probar la política.

Primero, puede crear un Pod con un Contenedor _no_ en modo `privileged`:

[subs="+attributes", console]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: unprivileged-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
EOF
----

Esto produce la siguiente salida:

[subs="+attributes", console]
----
pod/unprivileged-pod created
----

El Pod se crea con éxito.

Ahora, puede crear un Pod con al menos una bandera `privileged` de Contenedor:

[subs="+attributes", console]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
          privileged: true
EOF
----

La política deniega la creación del Pod y debería ver el siguiente mensaje:

[subs="+attributes", console]
----
Error from server: error when creating "STDIN": admission webhook "clusterwide-privileged-pods.kubewarden.admission" denied the request: Privileged container is not allowed
----

[NOTE]
====

Ambos ejemplos no definieron un `namespace`, lo que significa que el `namespace` `default` era el objetivo. Sin embargo, como pudo ver en el segundo ejemplo, la política todavía se aplica. Como se indicó anteriormente, esto se debe a que el alcance es de todo el clúster y no se dirige a un espacio de nombres específico.

====


== Desinstalar

Puede eliminar los recursos creados desinstalando los charts de `helm` de la siguiente manera:

[subs="+attributes", console]
----
helm uninstall --namespace kubewarden kubewarden-defaults
----

[subs="+attributes", console]
----
helm uninstall --namespace kubewarden kubewarden-controller
----

[subs="+attributes", console]
----
helm uninstall --namespace kubewarden kubewarden-crds
----

Después de eliminar los charts de `helm`, elimine el espacio de nombres de Kubernetes utilizado para desplegar la pila de {short-project-name}:

[subs="+attributes", console]
----
kubectl delete namespace kubewarden
----

[CAUTION]
====

{short-project-name} contiene un gancho de pre-eliminación de helm que elimina todos los `PolicyServer`s y `kubewarden-controller`s. Luego, el `kubewarden-controller` elimina todos los recursos, por lo que es importante que `kubewarden-controller` se esté ejecutando cuando se ejecute la desinstalación de helm.

====


{short-project-name} elimina los {validating-webhook-configuration}s y {mutating-webhook-configuration}s. Compruébelo con:

[subs="+attributes", console]
----
kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -l "kubewarden"
----

[subs="+attributes", console]
----
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io -l "kubewarden"
----

Si estos recursos no se eliminan automáticamente, elimínelos manualmente con el siguiente comando:

[subs="+attributes", console]
----
kubectl delete -l "kubewarden" validatingwebhookconfigurations.admissionregistration.k8s.io
----

[subs="+attributes", console]
----
kubectl delete -l "kubewarden" mutatingwebhookconfigurations.admissionregistration.k8s.io
----

== Conclusión

{cluster-admission-policy} es el recurso principal que un operador de clúster tiene que gestionar. El módulo `kubewarden-controller` se encarga automáticamente de la configuración del resto de los recursos necesarios para ejecutar las políticas.

== ¿Qué sigue?

¡Ahora está listo para desplegar {short-project-name}! Eche un vistazo a las políticas en https://artifacthub.io/packages/search?kind=13[artifacthub.io], en https://github.com/topics/kubewarden-policy[GitHub], o reutilice las políticas de Rego existentes como se muestra en los xref:tutorials/writing-policies/rego/01-intro-rego.adoc[siguientes capítulos].

.Lista completa de políticas disponibles en ArtifactHub
[%collapsible, subs="+macros"]
======

++++

<div class="artifacthub-widget-group" data-url="https://artifacthub.io/packages/search?kind=13&sort=relevance&page=1" data-theme="light" data-header="false" data-stars="false" data-color="#fe7c3f" data-responsive="true" data-loading="true"></div>

++++

======
