include::partial$variables.adoc[]
= Casos de uso de {project-name}
:revdate: 2025-11-10
:page-revdate: {revdate}
:sidebar_label: Use cases
:sidebar_position: 74
:description: A description of certain use cases for {project-name}.
:keywords: {project-name}, documentation, use cases, case studies
:doc-persona: kubewarden-all
:doc-type: explanation
:doc-topic: explanation

Estos son algunos ejemplos de casos de uso para las xref:/personas.adoc[personas] de {project-name}.

== Caso A: Como operador de Kubernetes, quiero asegurarme de que mi clúster sea seguro y cumpla con las normativas.

Despliego {project-name} y su configuración predeterminada con su chart de Helm `kubewarden-defaults`, en el espacio de nombres `kubewarden`. Esto despliega un PolicyServer predeterminado y ClusterAdmissionPolicies recomendadas en el espacio de nombres `kubewarden`, únicamente bajo el control del operador de Kubernetes.

Como operador, puedo agregar más PolicyServers bajo un espacio de nombres gestionado (como `kubewarden`) para distribuir la carga y la tolerancia a fallos.

Los operadores pueden desplegar más ClusterAdmissionPolicies y ClusterAdmissionPolicyGroups. Estos comprueban todos los recursos de Kubernetes, para cualquier tipo de operación (GET, CREATE, UPDATE, PATCH, DELETE, PROXY). Esto garantiza que las operaciones en el clúster sean seguras y cumplan con las normativas.

Estos incluyen:

* seguridad
* cumplimiento (de normas del sector o reglamentos de la empresa)
* optimización de recursos (a través de políticas de mutación)
* gobernanza de los entornos de Kubernetes (a través de etiquetas y convenciones de nomenclatura)
* mejores prácticas
* verificación de imágenes

Las expectativas de seguridad cambian con el tiempo. Los despliegues previamente correctos en el clúster pueden dejar de serlo. Sin embargo, {short-project-name} ya ha aceptado esas operaciones en el clúster. En estas situaciones, el operador puede desplegar la función de Escáner de Auditoría, un CronJob que se ejecuta periódicamente y evalúa los recursos existentes en el clúster. Esto comprueba que el clúster es seguro y cumple con las normativas incluso con el paso del tiempo.

El operador puede configurar las políticas en modo `monitor` en lugar de en modo `protect`, para aprender del estado del clúster sin bloquear las operaciones.

Los operadores pueden recibir información de las políticas y de la pila de {short-project-name} consumiendo registros e información de OpenTelemetry para métricas y trazabilidad.

== Caso B: Como operador de Kubernetes, quiero proporcionar un marco a mis usuarios de Kubernetes para que puedan autogestionarse en sus espacios de nombres.

Como operador, despliego {short-project-name} como en el Caso A para un conjunto de políticas de mi elección. Esto me proporciona una base segura en el clúster, que otros usuarios no pueden eludir.

Además del Caso A, tengo diferentes personas por espacio de nombres: quizás equipos, administradores de equipos, despliegues de prueba y otros. Permito que cada administrador de espacio de nombres se autogestione permitiéndoles desplegar PolicyServers en su espacio de nombres, junto con AdmissionPolicies y AdmissionPolicyGroups con espacio de nombres. Esta arquitectura significa que tienen el control de su PolicyServer y sus políticas. Las políticas solo se aplican a su espacio de nombres, y restringen el uso de recursos a su espacio de nombres.

También permite al operador segregar a los inquilinos ruidosos, reservando PolicyServers de alto rendimiento para aquellos inquilinos y tareas que necesitan un alto rendimiento y baja latencia, por ejemplo.

== Caso C: Como autor de políticas, quiero usar las herramientas y los lenguajes que conozco para escribir nuevas políticas.

{short-project-name} lo consigue soportando cualquier lenguaje que compile a WebAssembly como posibles lenguajes de destino para las políticas. Esto significa que los autores de políticas pueden reutilizar sus flujos de trabajo (`git`, CI, editores, revisiones por pares, etc.), y herramientas: lenguajes, bibliotecas de lenguajes, arneses y marcos de pruebas, etc.

Permite reutilizar Lenguajes Específicos de Dominio (como Rego, CEL, YAML+macros de Kyverno) o lenguajes de propósito general (como Go, Rust, C#, Javascript, cualquiera que compile a Wasm). {short-project-name} proporciona xref:/tutorials/writing-policies/index.adoc[SDKs] para algunos lenguajes como soporte de primera clase.

Las políticas de {short-project-name} pueden ser políticas simples o complejas xref:/explanations/context-aware-policies.adoc[conscientes del contexto]. Las políticas conscientes del contexto también se utilizan para interactuar con cargas de trabajo separadas (por ejemplo, para obtener información de un servicio de larga duración de un escáner de imágenes).

== Caso D: Como integrador de sistemas, quiero reutilizar {short-project-name} como parte de mi solución de seguridad y cumplimiento.

Como integrador de sistemas, quiero reutilizar {short-project-name}, y posiblemente reutilizar otras soluciones incluyéndolas en {short-project-name}.

Como integrador de sistemas, puedo reutilizar partes de {short-project-name}. Por ejemplo, el `policy-server`, para vigilar los recursos, internos o externos al clúster de Kubernetes a través de la función de xref:/howtos/raw-policies.adoc["políticas sin procesar"].

Los integradores de sistemas pueden optar por desplegar el `kubewarden-controller` o gestionar las CRD por su cuenta. Pueden optar por desplegar o escalar el Escáner de Auditoría según sea necesario.

Los integradores de sistemas pueden crear nuevos componentes. Por ejemplo, un escáner de imágenes, e interactuar con él a través de una política consciente del contexto, sin tener una implementación monolítica en un controlador de Kubernetes.

== No objetivos

{short-project-name} no pretende:

- Sustituir las funciones de seguridad integradas de Kubernetes, sino complementarlas:
  - {short-project-name} proporciona migración desde PSPs.
  - Puede reutilizar ValidatingAdmissionPolicies y políticas CEL con la `cel-policy` de {short-project-name}.
  - Las políticas de {short-project-name} pueden ser mutantes, mientras que la Admisión de Seguridad de Pods no puede.
  - Las políticas de {short-project-name} se benefician de las características de la pila de {short-project-name} (escáner de auditoría, telemetría, gestión de CRD).
- Proporcionar seguridad en tiempo de ejecución como detección de intrusiones o aislamiento de contenedores en tiempo de ejecución.
- Proporcionar protección del sistema anfitrión de los clústeres.
- Proporcionar una flexibilidad de ejecución de políticas infinita. Para evitar ataques DoS, los tiempos de procesamiento de las políticas son limitados.
