include::partial$variables.adoc[]
= 什么是 {project-name}？
:revdate: 2025-11-10
:page-revdate: {revdate}
:description: Introducing {project-name}, a SUSE® Rancher Prime product.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["introduction"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"]
:sidebar_label: Introduction
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} 是一个 Kubernetes 策略引擎。它的目标是成为 Kubernetes 的通用策略引擎。

{intro-paragraph}

现在这里有一个指向 rancher-product-docs 概述的链接：

* xref:rancher-manager:zh:/about-rancher/overview.adoc[概述]

== {project-name} 有何帮助？

{short-project-name} 为 Kubernetes 环境中的策略准入和执行提供了灵活性。

=== 优势和价值

- 使用任何能够生成 https://webassembly.org[WebAssembly] 二进制文件的编程语言来编写您的策略。
- WebAssembly 实现了跨处理器和操作系统的策略兼容性。
- 重用来自其他策略引擎的策略，而无需重写它们。
- 使用标准和安全的机制（例如 https://opencontainers.org[OCI] 兼容的注册中心）分发策略。
- 在准入时强制执行策略可确保只运行合规的工作负载。
- {short-project-name} 审计扫描器会随着时间的推移主动并持续地检查策略执行情况。
- 使用 https://slsa.dev[SLSA]（软件工件供应链级别）工具和实践来验证策略。
- {project-name} 提供了一种全面的准入策略管理方法。
- CNCF 成员资格以及不断壮大的开源社区和生态系统可帮助 {short-project-name} 实现透明、协作和改进。

=== 使用案例

- 安全加固。例如，强制执行限制容器权限的策略、强制执行网络策略或阻止不安全的镜像注册中心。
- 合规性审计。确保工作负载符合组织或法规标准和最佳实践。
- 资源优化。强制执行资源限制和配额。

有关使用案例的更多文档，请参阅 xref:use-cases.adoc[使用案例] 页面。

== 初次接触 {short-project-name}？

如果您是 {short-project-name} 项目的新手，请从 xref:quick-start.adoc[快速入门指南] 和 xref:explanations/architecture.adoc[架构] 页面开始。然后，这取决于您的兴趣所在。对于策略开发人员，教程中有特定于语言的部分。对于集成商和管理员，有一个“操作方法”部分。解释部分包含有用的背景材料。还有一个 xref:glossary.adoc[词汇表]。

== 什么是 WebAssembly？

正如 https://webassembly.org/[WebAssembly 官方网站] 所述：

____
WebAssembly（缩写为 Wasm）是一种用于基于堆栈的虚拟机的二进制指令格式。Wasm 被设计为编程语言的可移植编译目标，支持在 Web 上部署客户端和服务器应用程序。
____

Wasm 最初被构想为浏览器“扩展”。然而，WebAssembly 社区正在努力允许在浏览器之外执行 Wasm 代码。

== 为何使用 WebAssembly？

用户可以使用他们喜欢的编程语言编写 Kubernetes 策略，前提是其工具链可以生成 Wasm 二进制文件。

Wasm 模块是可移植的，一旦构建，它们就可以在任何类型的处理器架构和操作系统上运行。例如，在 Apple Silicon 上开发和构建的策略无需转换即可在 AMD64/Intel64 Linux 上运行。

策略作者可以重用他们的技能、工具和最佳实践。策略是“传统”程序，可以有可重用的块（常规库）。您可以对它们进行 lint 和测试，还可以将它们插入当前的 CI 和 CD 工作流中。

== 策略分发

您可以使用标准 Web 服务器为 {short-project-name} 策略提供服务，或者，更好的是，您可以将它们作为 https://github.com/opencontainers/artifacts[OCI 工件] 发布在 OCI 兼容的注册中心中。

ifeval::["{build-type}" == "community"]

== 供应商中立

{short-project-name} 是由 CNCF 定义的 link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/[供应商中立] 项目。

endif::[]
